{
 "title": "jitsi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "NUMERI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Part. NOW",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jitsi_participants" }
   ]
  },
  {
   "title": "Part. MAX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "jitsi_participants" }
   ]
  },
  {
   "title": "Media dei partecipanti",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jitsi_participants" }
   ]
  },
  {
   "title": "Conf. NOW",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jitsi_conferences" }
   ]
  },
  {
   "title": "Conf. MAX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "jitsi_conferences" }
   ]
  },
  {
   "title": "MEDIA delle conferenze",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jitsi_conferences" }
   ]
  },
  {
   "title": "max bitrate download",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "Kbits",
   "valueName": "max",
   "targets": [
    { "expr": "jitsi_bit_rate_download" }
   ]
  },
  {
   "title": "max bitrate upload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "Kbits",
   "valueName": "max",
   "targets": [
    { "expr": "sum(jitsi_bit_rate_upload)" }
   ]
  },
  { "title": "GRAFICI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "total participants / conferences",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(jitsi_participants)", "legendFormat": "total participants" },
    { "expr": "sum(jitsi_conferences)", "legendFormat": "total conferences" }
   ]
  },
  {
   "title": "Bitrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    { "expr": "jitsi_bit_rate_download", "legendFormat": "Download" },
    { "expr": "jitsi_bit_rate_upload", "legendFormat": "Upload" }
   ]
  }
 ]
}