--- 
global: 
  external_labels: 
    monitor: "iorestoacasa.work monitoring"
  scrape_interval: 10s
scrape_configs: 
  - 
    job_name: prometheus
    static_configs: 
      - 
        targets: 
          - "localhost:9090"
  - job_name: monitor
    file_sd_configs: 
      - files:
        - 'targets.json'
        refresh_interval: 30s